### ISSUE TITLE
I cannot understand why the input dimension is (num_step, batch_size). I can only see that, before entering the function, the dimension of the input is (batch_size, num_step).

### ISSUE THREAD

**Issue by turboLJY** [nijianmo/textExpansion#2]
https://github.com/nijianmo/textExpansion/blob/50f8ecce33711f38e5ca419cd727a94e99aa8018/expansionNet/model.py#L41

**Comment by nijianmo** [comment]
Hi, you can check out the reason by searching how RNN input is defined.

https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/rnn.py

By default, it is defined as (seq_len, batch, input_size). You can change to (batch, seq_len, input_size) by setting batch_first=True when initializing a RNN.
